version: '3.8'

services:
  todo-app:
    build: ./
    command: ./start
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - SIGNING_KEY=${SIGNING_KEY}

  db:
    restart: always
    image: postgres:latest
    volumes:
    - ./.database/postgres/data:/var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
    - 5436:5432
