version: '3.8'

services:
  todo-app:
    build: ./
    command: ./wait-for-postgres.sh db ./todo-app
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - .env

  db:
    restart: always
    image: postgres:13.5
    volumes:
    - ./.database/postgres/data:/var/lib/postgres/data
    env_file:
      - .env
    ports:
    - 5432:5432
